name: windows-integration-testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@master
        with:
          submodules: true
          fetch-depth: 0
      - name: Compile programs
        run: |
          bash .ci\compile.bat